name: Publish Package to npmjs

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: copy README
        uses: canastro/copy-file-action@master
        with:
          source: "README.md"
          target: "@lib/README.md"
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./@lib/package.json"
